 # Sigmoid implementation

In [ ]:
import torch
from torch.autograd import Function
from torch.autograd import Variable

In [ ]:
#pure python

import numpy as np
class Sigmoid :
  def forward(self,x):
    self.x=x
    return(1/1+np.exp(-x))
  def backward(self,grad):
    grad_input=self.x * (1+self.x) * grad
    return grad_input


In [ ]:
#using autograd


class Sigmoid:
  @staticmethod
  def forward(ctx,x):
    output=1/(1+torch.exp(-x))
    ctx.save_for_backward(output)
    return output
  @staticmethod
  def backward(ctx,grad_output):
    output, = ctx.saved_tensors
    grad_x= output*(1-output) * grad_output
    return grad_x



# Relu implementation

In [ ]:
class ReLU(torch.autograd.Function):
  @staticmethod
  def forward(ctx,x):
    ctx.save_for_backward(x)
    return x.clamp(min=0)
  def backward(ctx,grad_output):
    x,=ctx.saved_tensors
    grad_x=grad_output.clone()
    grad_x[x<0]=0
    return grad_x


In [ ]:
#Example for relu
x = Variable(torch.randn(3, 3), requires_grad=True)
relu=ReLU.apply
print(x)
# Initialize the custom ReLU function
relu = ReLU.apply
# Forward pass
output = relu(x)
print("Output after forward pass:")
print(output)
grad_output = torch.randn(3, 3)
print(grad_output)
output.backward(grad_output)
grad_x = x.grad
print("\nGradient with respect to x:")
print(grad_x)

tensor([[-1.3286, -0.3257,  0.6541],
        [ 0.4730,  0.1508,  1.6782],
        [ 0.4746,  0.9059,  0.0912]], requires_grad=True)
Output after forward pass:
tensor([[0.0000, 0.0000, 0.6541],
        [0.4730, 0.1508, 1.6782],
        [0.4746, 0.9059, 0.0912]], grad_fn=<ReLUBackward>)
tensor([[-0.0046, -0.0621,  0.0312],
        [-1.6013,  0.5070, -0.0314],
        [ 0.2353,  1.3479,  0.7803]])

Gradient with respect to x:
tensor([[ 0.0000,  0.0000,  0.0312],
        [-1.6013,  0.5070, -0.0314],
        [ 0.2353,  1.3479,  0.7803]])


# Arctanh implementation

In [ ]:
class Arctanh(Function):
    @staticmethod
    def forward(ctx, x):
        ctx.save_for_backward(x)
        r = (torch.log(1 + x) - torch.log(1 - x)) * 0.5
        return r  # Return the computed result

    @staticmethod
    def backward(ctx, grad_output):
        x, = ctx.saved_tensors
        x_grad = grad_output / (1 - x**2)
        return x_grad

In [ ]:
#testing code with gradcheck
xT = torch.abs(torch.tensor([[0.11, 0.19, 0.57]], requires_grad=True)).type(torch.DoubleTensor)
f=Arctanh.apply
test=torch.autograd.gradcheck(lambda t:f(t),xT)
print(test)

True
